name: Python Static Analysis and Dummy Test

on:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest

    - name: Run flake8 static analysis
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --format=html --htmldir=flake8-report

    - name: Upload flake8 HTML report
      uses: actions/upload-artifact@v4
      with:
        name: flake8-report
        path: flake8-report

    - name: Run dummy test with pytest
      run: |
        pytest

